### ISSUE TITLE
Cannot address `add` in the edit file

### ISSUE THREAD

**Issue by nomeata** [antalsz/hs-to-coq#11]
Because `add` is a token keyword in the happy parser, I cannot write
```
skip add
```

Is there a way to avoid that?

**Comment by antalsz** [comment]
Is this resolved now that we're post-renamer?

**Comment by nomeata** [comment]
No, it is a problem with the lexer in the happy-syntax, I believe. It thinks `add` is keyword of the edit language.
```
skip skip
```
should show the same behaviour.

**Comment by antalsz** [comment]
But don't we now need to

    skip Foo.add

instead?

**Comment by nomeata** [comment]
That might be a feasible work-around. (I actually think that `skip` is not properly qualified yet, thought, which is a separate bug).

**Comment by nomeata** [comment]
Oh, misread your sentence. No! We currently still specify `skip`s with their basenames (and I think we are not systematic about whether it’s the Coq name or the Haskell name).

I think a post-paper cleanup is to be very precise in where we want Haskell names, qualified Haskell names, optionally qualified Haskell names, and the same for Coq names; both in the Code and hence in the edits.

**Comment by antalsz** [comment]
Okay!  Then I think this will actually be solved by that deep cleaning of the code, which 100% needs to happen.
