### ISSUE TITLE
hs-to-coq doesn't accept minimal implementation of Ord in terms of (<=)

### ISSUE THREAD

**Issue by emarzion** [antalsz/hs-to-coq#116]
The following code is rejected by hs-to-coq with the error message ```The method `GHC.Base.compare' has no definition and no default definition```  :
```
module Test where

data Test = A | B deriving Eq

instance Ord Test where
  A <= _ = True
  B <= B = True
  _ <= _ = False
```

**Comment by sweirich** [comment]
Ord is treated specially by hs-to-coq (and by GHC).  I'm adding a default definition for GHC.Base.compare to https://github.com/antalsz/hs-to-coq/blob/master/src/lib/HsToCoq/ConvertHaskell/BuiltIn.hs now.
