### ISSUE TITLE
coq-haskell ?

### ISSUE THREAD

**Issue by spitters** [antalsz/hs-to-coq#122]
Is there (a planned) interaction between coq-haskell and hs-to-coq?
https://github.com/jwiegley/coq-haskell

by @jwiegley 

It seems like your structural-isomorphism-plugin may try to do something like that, but it's not documented.

**Comment by sweirich** [comment]
We have no current plans to integrate these projects (beyond the experience that John has already contributed to the creation of the base library: https://github.com/antalsz/hs-to-coq/tree/master/base).

**Comment by spitters** [comment]
Thanks. I made a link in the [stdlib2 discussion](https://github.com/coq/stdlib2/wiki/Other-%22standard%22-libraries). I'm wondering how/whether we would like to connect the haskell specific development with the corresponding idiomatic Coq development. Parametricity, as in CoqEAL, comes to mind.

**Comment by jwiegley** [comment]
If anything, coq-haskell ought to become an ever-thinner wrapper around hs-to-coq's base library, since it represents a more faithful representation of the Haskell libraries I'm trying to mimick.
