### ISSUE TITLE
Anomaly: Unable to handle arbitrary u+k <= v constraints.

### ISSUE THREAD

**Issue by nomeata** [antalsz/hs-to-coq#2]
If I try to load `core.v` (version 8a65ab013185c3ec99751ee82f4c531c559b30cb) in coqide, it gives the error message

> Anomaly: Unable to handle arbitrary u+k <= v constraints. Please report at
> http://coq.inria.fr/bugs/.

as soon as the focus reaches `Inductive Expr`. Is something wrong with the extracted Coq or with my local Coq setup (Coq 8.6)?

**Comment by nomeata** [comment]
This patch makes the problem go away:
```
diff --git a/core.v b/core.v
index e808ab3..fd0e462 100644
--- a/core.v
+++ b/core.v
@@ -1533,7 +1533,7 @@ Reserved Notation "'Arg'".
 
 Inductive Expr : (forall b, Type) := Mk_Var : (forall {b}, (Id -> (Expr b)))
                                   |  Mk_Lit : (forall {b}, (Literal -> (Expr b)))
-                                  |  Mk_App : (forall {b}, (((Expr b)) -> (((Arg b)) -> (Expr b))))
+                                  |  Mk_App : (forall {b}, (((Expr b)) -> (((Expr b)) -> (Expr b))))
                                   |  Mk_Lam : (forall {b}, (b -> (((Expr b)) -> (Expr b))))
                                   |  Mk_Let : (forall {b}, (((Bind b)) -> (((Expr b)) -> (Expr b))))
                                   |  Mk_Case : (forall {b},
```

**Comment by antalsz** [comment]
That's aggravating.  My guess is it's a Coq 8.6 thing – I'm still on 8.5.  I'll upgrade and test, since we want to pin to 8.6.  This fix isn't sustainable, though, since it's to the autogenerated code.

**Comment by sweirich** [comment]
The issue seems to be a bug in Coq's universe polymorphism. (I don't know how to work around it though).  

Why do we have the Synonym thing anyways?

Why not use this version:
```
Inductive Expr : forall b, Type := Mk_Var : (forall {b}, Id -> Expr b)
                                  |  Mk_Lit : (forall {b}, Literal -> Expr b)
                                  |  Mk_App : (forall {b}, (Expr b) -> (Arg b) -> Expr b)
                                  |  Mk_Lam : (forall {b}, b -> (Expr b) -> Expr b)
                                  |  Mk_Let : (forall {b}, (Bind b) -> (Expr b) -> Expr b) 
                                  |  Mk_Case : (forall {b}, (Expr b) -> b -> Type_ -> (list (Alt b)) -> Expr b)
                                  |  Mk_Cast : (forall {b}, (Expr b) -> Coercion -> Expr b)
                                  |  Mk_Tick : (forall {b}, (Tickish Id) -> (Expr b) -> Expr b)
                                  |  Mk_Type : (forall {b}, Type_ -> Expr b)
                                  |  Mk_Coercion : (forall {b}, Coercion -> Expr b)
with Bind : (forall b, Type) := Mk_NonRec : (forall {b}, b -> (Expr b) -> Bind b)
                             |  Mk_Rec : (forall {b}, (list (b * (Expr b))) -> Bind b)
where "'Arg'" := Expr
and   "'Alt'" := (fun b => (AltCon * list b * Expr b)%type).
```

**Comment by sweirich** [comment]
Recording another solution to this problem. If we make the argument to Expr a parameter instead of an Index, and freshen the variable used in Arg we can write it this way: 
```
Reserved Notation "'Arg'".

Inductive Expr (b : Type) : Type := Mk_Var :  Id -> Expr b
                                  |  Mk_App : (Expr b) -> (Arg b) -> Expr b
                                  |  Mk_Lam : b -> (Expr b) -> Expr b
where "'Arg'" := (Synonym Arg__raw (fun c => (Expr c)%type)).
```

Note that if the last line reads
```
where "'Arg'" := (Synonym Arg__raw (fun b=> (Expr b)%type)).
```
we get the (nonsense) error message:
```
Error: A parameter of an inductive type b is not allowed to be used as a bound variable in the type of its constructor.
```
@antalsz Did this message prompt you to make `b` an index instead of a parameter in the first place?

**Comment by antalsz** [comment]
See #3 – maybe we can just switch to a parameter!  The `b` vs. `c` thing is (a) completely ridiculous, and (b) handled in [`HsToCoq.ConvertHaskell.Declarations.TyCl.convertDeclarationGroup`](https://github.com/antalsz/hs-to-coq/blob/1b456f488c7152ab66aed056f04c738aa1f5aa5a/hs-to-coq/src/lib/HsToCoq/ConvertHaskell/Declarations/TyCl.hs#L168-L176) (lines 168–176, using the `avoidParams` local function).

**Comment by sweirich** [comment]
OK. I'll take a look.

**Comment by sweirich** [comment]
Ok, just dropping 
```
data type arguments Expr (indices: b)
data type arguments Bind (indices: b)
```
from edits.txt works! 

I will close this issue (and #3).
