### ISSUE TITLE
Operators as function parameters

### ISSUE THREAD

**Issue by sweirich** [antalsz/hs-to-coq#22]
(This is not urgent, marking for future reference).

`Data.Function` has this annoying definition that we can't currently handle.

```
on :: (b -> b -> c) -> (a -> b) -> a -> a -> c
(.*.) `on` f = \x y -> f x .*. f y
```

**Comment by nomeata** [comment]
This is working now, since 647ce61ec90b6f68c4ecfc0db48f79a3d2ce446b.
