### ISSUE TITLE
Cannot find class information for Foldable/Traversable/Monoid

### ISSUE THREAD

**Issue by sweirich** [antalsz/hs-to-coq#26]
When I translate ghc/compiler/Util/Pair.v   (in examples/ghc)

I get these messages:

```
(* Translating `instance Data.Foldable.Foldable Pair' failed: OOPS! Cannot find
   information for class "Data.Foldable.Foldable" unsupported *)
 
(* Translating `instance Data.Traversable.Traversable Pair' failed: OOPS! Cannot
  find information for class "Data.Traversable.Traversable" unsupported *)

(* Translating `instance forall {a}, forall `{GHC.Base.Monoid a},
  GHC.Base.Monoid (Pair a)' failed: OOPS! Cannot find information for class
 "GHC.Base.Monoid" unsupported *)
```
Do we need to do something special to tell hs-to-coq where to find these classes?

**Comment by antalsz** [comment]
We need to add support for this in `hs-to-coq` as part of #23.

**Comment by nomeata** [comment]
Temporarily we can do what we do for `Make` etc.: Hardcode them in the code, as we do for `Monad` etc.

**Comment by sweirich** [comment]
Where is this hardcoded? This is not urgent (yet).

**Comment by nomeata** [comment]
https://github.com/antalsz/hs-to-coq/blob/master/hs-to-coq/src/lib/HsToCoq/ConvertHaskell/Monad.hs#L109

**Comment by sweirich** [comment]
Thanks.  We can wait for #23 now, but if it is blocking, I'll know what to do.

**Comment by nomeata** [comment]
Closing this in favor of #23
