### ISSUE TITLE
Need a before/after edit

### ISSUE THREAD

**Issue by sweirich** [antalsz/hs-to-coq#27]
I want to be able to insert arbitrary Coq code right before or after a particular point in the file. Not just at the preamble. 

```
after blah {{ Definition ...  }}
```
I don't think we need to parse the part between the {{ ... }},  just splice it into the file at the appropriate point.

**Comment by sweirich** [comment]
This could also be in conjunction with `replace`.

**Comment by nomeata** [comment]
Doesn't `add` do that? `hs-to-coq` should put things in the right place automatically.

**Comment by sweirich** [comment]
What is the syntax for `add`?

**Comment by nomeata** [comment]
```
add Definition foo x := bar x.
```
(Same as for replace)

**Comment by nomeata** [comment]
Also see `examples/tests/AddAndReplace.hs` and `examples/tests/AddAndReplace/edits` for examples.

**Comment by sweirich** [comment]
Does `redefine` need to be all on one line? How much of the Coq parser does it implement?

I'm getting 
```
Could not parse module-edits/SrcLoc/edits: unexpected closing delimeter `}'
```
for the edit
```
redefine Local Definition instance_forall___GHC_Base_Eq__e____GHC_Base_Eq__l___GHC_Base_Eq___GenLocated_l_e__op_zeze__ {inst_l}{inst_e}  `{GHC.Base.Eq_  inst_e} `{GHC.Base.Eq_ inst_l}    : GenLocated inst_l inst_e -> GenLocated inst_l inst_e -> bool :=  fun arg_253__ arg_254__ =>    match arg_253__ , arg_254__ with  | Mk_L a1 a2 , Mk_L b1 b2 => (andb ((GHC.Base.op_zeze__ a1 b1))     ((GHC.Base.op_zeze__ a2 b2)))    end.
```

**Comment by nomeata** [comment]
It does not like `\`{…}`, hence write `{_ : …}`. Not sure it implements `match` either, sorry.

**Comment by sweirich** [comment]
switching to `{_ : _}` changed the error message. Now it reads
```
Could not parse module-edits/SrcLoc/edits: unexpected operator `->'
```
Why do we need to parse the replacement code?

**Comment by nomeata** [comment]
For things like figuring out which variables are used (for order of declarations and import statements).

**Comment by nomeata** [comment]
If you cannot work around it using helper functions in the preamble (e.g. to do the pattern match), then yes.

It should not be too hard to extend the parser if you have used `happy` before. `Parsers.y` is the parser, there is no separate lexer, and `Gallina.hs` contains the AST.

**Comment by sweirich** [comment]
This cannot be worked around with helper functions in the preamble.  We're deriving Eq for a datatype definition, so the datatype definition won't be in scope then.

The same arguments against unparsed Coq in the middle of the file should also apply to the preamble...

**Comment by nomeata** [comment]
> The same arguments against unparsed Coq in the middle of the file should also apply to the preamble...
The preamble does not need to be sorted by hs-to-coq, and you are expected to import stuff there by hand.

(A version of `add` that just adds an opaque string as the right hand side is not unfeasible. You’d have to use `order` statements to move it into the right spot, but why not.)

**Comment by sweirich** [comment]
With parser extensions, `add`, and the `midamble` I'm going to mark this as resolved.
