### ISSUE TITLE
Cannot generate instance for -> in Control.Category

### ISSUE THREAD

**Issue by sweirich** [antalsz/hs-to-coq#40]
If we switch from HANDMOD to MODULES for Control.Category, the translation succeeds but we miss an instance

```
(* Translating `instance Category GHC.Prim.arrow' failed: OOPS! Cannot find
   information for class "Category" unsupported *)
```

The Category class is defined in the same file so the class information should be available.

**Comment by sweirich** [comment]
Is this related to the recent change you have made to type classes?

**Comment by nomeata** [comment]
No, my change should be completely independent of the type class information handling

**Comment by nomeata** [comment]
Ah, but it might be related to `class kinds` – if I remove that edit it knows about the class.

**Comment by nomeata** [comment]
Found and fixed, thanks for the report.
