### ISSUE TITLE
Bugs while translating guards and pattern matchings

### ISSUE THREAD

**Issue by lastland** [antalsz/hs-to-coq#46]
I have created a minimal example that can reproduce this bug under `examples/guard`.

The Haskell file contains the following three functions:

```Haskell
f :: Int -> Int
f x | x == 1    = 1
    | otherwise = 2

g :: Int -> Int
g 1 = 1
g _ = 2

h :: Int -> Int
h x = if x == 1 then 1 else 2
```

`hs-to-coq` fails to translate `f`.

It can translate `g` but the translated Coq file cannot be compiled (because the translated code uses `==`, which is a notation must be imported from `GHC.Base`).

It can successfully translate `h`.

**Comment by lastland** [comment]
Changing `f` to:
```Haskell
f :: Int -> Int
f x | True    = 1
    | otherwise = 2
```
and `hs-to-coq` still fails to translate `f`.

**Comment by lastland** [comment]
But `hs-to-coq` can successfully translate the following `f`:
```Haskell
f :: Int -> Int
f x | x == 1 = 1
f _ = 2
```

**Comment by sweirich** [comment]
Code for translating pattern matches with guards is here
https://github.com/antalsz/hs-to-coq/blob/master/src/lib/HsToCoq/ConvertHaskell/Expr.hs
