### ISSUE TITLE
examples/successors make error

### ISSUE THREAD

**Issue by aogrcs** [antalsz/hs-to-coq#47]
*** No rule to make target '../../base/GHC/Base.vo', needed by 'Control/Applicative/Successors.vo'.

**Comment by lastland** [comment]
Hi, you will need to run `make` in `base` first. Can you try, for example, `make -C ../../base` (or just `cd` to `base`, and then `make`)?

**Comment by aogrcs** [comment]
I cd to base then I make, but I said that could not find ssreflect

**Comment by sweirich** [comment]
Sorry about that. I just updated the toplevel README.md file with instructions to install ssreflect.

**Comment by aogrcs** [comment]
Just "opam install coq-mathcomp-ssreflect.1.6.1" worked, "opam install coq.8.6 coq-mathcomp-ssreflect.1.6.1" did not work, maybe caused by the opam source or the network. I also found the link
https://stackoverflow.com/questions/43955082/how-to-install-ssreflect-and-mathcomp-in-linux#
It did not set the coq version and installed coq 8.7, neither did it.
Thanks for your patient!

**Comment by sweirich** [comment]
Were you able to get it work?

**Comment by aogrcs** [comment]
Yes, it did work, thanks

**Comment by sweirich** [comment]
Ok, closing issue. Let us know if you have other questions!
