### ISSUE TITLE
Skipping impossible guard condition/ Skipping certain macro expansions

### ISSUE THREAD

**Issue by lastland** [antalsz/hs-to-coq#48]
`Data.Set` contains the following definition:
```Haskell
elem = go
  where STRICT_1_OF_2(go)
        go _ Tip = False
        go x (Bin _ y l r) = x == y || go x l || go x r
```
where `STRICT_1_OF_2` is a macro defined as:
```C
#define STRICT_1_OF_2(fn) fn arg _ | arg `seq` False = undefined
```
It is used to improve performance by avoiding unneeded laziness, but this does not matter in the translated Coq version, so I would like to skip this macro expansion, as expanding that macro raises the complexity of the function, and introduces `undefined`.

An alternative way to handle this problem is that if we have some heuristics to tell the condition here (```arg `seq` False```) always evaluates to `False`, we can ignore this branch during translation.

**Comment by lastland** [comment]
@nomeata suggested to pass something like `--ghc -D"STRICT_1_OF_2=-- "` to the tool, but it does not seem to work. It looks like the definitions in `containers.h` will overwrite what we passed to ghc:
```
containers/include/containers.h:44:9: error:
     warning: 'STRICT_1_OF_2' macro redefined [-Wmacro-redefined]
#define STRICT_1_OF_2(fn) fn arg _ | arg `seq` False = undefined
        ^

<built-in>:6:9: error:  note: previous definition is here
#define STRICT_1_OF_2 --
        ^
1 warning generated.
```

**Comment by nomeata** [comment]
This currently does not really block the translations, does it? I.e. it is ugly to have this pattern and the `undefined`, but you are not blocked due to it?

**Comment by lastland** [comment]
That's right. I'm not blocked.

**Comment by nomeata** [comment]
> An alternative way to handle this problem is that if we have some heuristics to tell the condition here (arg `seq` False) always evaluates to False, we can ignore this branch during translation.

I believe we are doing this since a while now, closing.
