### ISSUE TITLE
Precedence bug

### ISSUE THREAD

**Issue by sweirich** [antalsz/hs-to-coq#5]
For the following Haskell source:
```
eqString :: String -> String -> Bool
eqString []       []       = True
eqString (c1:cs1) (c2:cs2) = c1 == c2 && cs1 `eqString` cs2
eqString _        _        = False
```
The output I get for the RHS on the second line is 
```
 (eqString (andb (c1 == c2) cs1) cs2)
```
instead of 
```
 (andb (c1 == c2) (eqString cs1 cs2))
```
(To test, uncomment `skip eqString` in examples/ghc-base/Base/edits`)
Where should I look to debug this issue?

**Comment by antalsz** [comment]
Oh, that's surprising to me… it may have to do with a change in representation in 8.0.2.  Take a look in `convertExpr`, although if I'm right, the only way to solve this problem might be to move after the renamer.

**Comment by antalsz** [comment]
@nomeata: You have a better sense of the renamer, I think, so I'm dragging you in :-)

**Comment by antalsz** [comment]
OK, I was correct (unfortunately).  From [the GHC wiki](https://ghc.haskell.org/trac/ghc/wiki/Commentary/Compiler/Renamer):

> In addition, the renamer does the following things:
>
>   * Sort out fixities. The parser parses all infix applications as **left-associative**, regardless of fixity. For example "`a + b * c`" is parsed as "`(a + b) * c`". The renamer re-associates such nested operator applications, using the fixities declared in the module.
>  * …

So it looks like we're going to have to move there.  Luckily, the other two items in that list are also useful (dependency analysis and lexical error checking).  Unluckily, this'll be a pain….

I'm closing this issue and opening a new one about moving after the renamer.
