### ISSUE TITLE
Notation for "<" in GHC/Base.v

### ISSUE THREAD

**Issue by sweirich** [antalsz/hs-to-coq#53]
The midamble.v file for GHC.Base defines the notation

```
Infix "<" := (op_zl__) (no associativity, at level 70).
```
However, this notation conflicts with Coq's default notation for `lt`, the less-than proposition. 
Furthermore, this notation is not defined in a notation scope or in a submodule, so any file that imports the Prelude imports it. 

I prefer using the notation "<?" for this operation (in line with the rest of Coq's libraries) instead of Haskell's notation. This makes it more clear that it is a bool returning function, not a prop. Others may disagree --- please discuss.

But, regardless, we should edit Base to make this notation more controllable.

**Comment by nomeata** [comment]
Doesn’t `<?` also clash with Coq’s notation for the boolean predicate?

I am fine with any name. Just make sure the method is renamed consistently (i.e. to `op_zlzq__`), as this correspondence is now an invariant. For a generated method definition, this should just work out of the box:

   rename value GHC.Classes.>   = GHC.Base.>?

Since this is a manual definition, you have to manually adjust the method name and notation  in `GHC.Base`’s midamble. But that should do the trick.

**Comment by sweirich** [comment]
I know about the clash. That is why I want to have a discussion instead of unilaterally changing it. 

We also should be putting these (and other) notations in a scope.

**Comment by nomeata** [comment]
*shrug* if the clash with `<` it gets in the way of your work but `<?` works nice, then just change it. I don’t think this needs too much discussion. (Especially as it is “just” an edit, and not something hardcoded in the tool.)

> We also should be putting these (and other) notations in a scope.

I just read through https://coq.inria.fr/refman/syntax-extensions.html#scopes, but it is not immediately clear to me how to best make use of that. What do you have in mind?

(A guess: Declare all our notations in scope `hs` and `Open Scope hs` by default. This allows users to use `(a < b)%hs` and `(a < b)%type` (or is it `(a < b)%nat`) to disambiguate. And after `Close Scope hs` all notation is disabled, which can be useful for debugging.)

**Comment by antalsz** [comment]
Ssreflect uses `<` for computational/Boolean equality, which combined with Haskell's use in the same way, pushes me a little to sticking with Haskell's approach.  (There's a bit of "best of a bad bunch" going on with the choices here anyway.)  And yes, we should *definitely* put everything in our own scope.

**Comment by nomeata** [comment]
I think this is obsolete, and either not an issue any more, or an issue that can be fixed with a single `rename` edit.
