### ISSUE TITLE
Axiomatize module should use translated types in axioms

### ISSUE THREAD

**Issue by sweirich** [antalsz/hs-to-coq#56]
`ghc/lib/Module.v` is the output of `axiomatize Module`.

The types of all of the definitions in this module are overly generic. Instead of 
```
Axiom stableModuleNameCmp : forall {A : Type}, A.
```
I would like it to produce something like this:
```
Axiom stableModuleNameCmp : ModuleName -> ModuleName -> comparison
```
As we are translating the type definitions already, perhaps we can also translate the types in the axioms too. This will mean a little more work when axiomatizing (need to skip defs with types that we don't care about) but will produce a more useful output in the end.

**Comment by antalsz** [comment]
I believe this is done now.
