### ISSUE TITLE
Cannot process modules named "Type"

### ISSUE THREAD

**Issue by sweirich** [antalsz/hs-to-coq#58]
see examples/tests/TypeClient.hs

**Comment by nomeata** [comment]
JFTR, it works if the module is named `Foo.Type` or `Top.Type`. It really is just `Type` on its own that causes problems.

**Comment by nomeata** [comment]
@sweirich does your `rename module` feature fix that?

**Comment by sweirich** [comment]
Yes, ideally.

**Comment by nomeata** [comment]
Ah, I see you have a test case. Great; it works as expected.
