### ISSUE TITLE
Link at top is broken

### ISSUE THREAD

**Issue by ranjitjhala** [antalsz/hs-to-coq#65]
Hi all, 

quick heads up; the link at the top of the repo, namely:

  http://www.deepspec.org/research/Haskell/

returns "Not found"?

Best!

Ranjit.

**Comment by sweirich** [comment]
Thanks!  The correct link is https://deepspec.org/entry/Project/Haskell+CoreSpec

**Comment by lastland** [comment]
@antalsz Looks like you are the only one who can update that?

**Comment by antalsz** [comment]
Yep, thanks!  Fixed :-)
