### ISSUE TITLE
newtype default translation does not make Coq happy

### ISSUE THREAD

**Issue by abailly** [antalsz/hs-to-coq#72]
Hello, 
I am currently experimenting with `hs-to-coq`. I am not very knowledgeable with Coq although I know quite a bit of Haskell. I am running into the following error:
```
Error: The following names are used both as type names and constructor names:
Timestamp.
```

The translated code is:

```
Inductive Timestamp : Type := Timestamp : GHC.Integer.Type.Integer -> Timestamp.
```

**Comment by nomeata** [comment]
Haskell has two namespaces, while Coq has one, so if the same name occurs in both name spaces in Haskell, that breaks Coq. We decided that it’s best if the user decided which of the two to rename, and to what, so you’ll have to manually intervene.

Create a “edit file” with this content
```
rename value Timestamp = MkTimeStamp
```
and pass that file via `-e` to `hs-to-coq`.

And let us know of any other problems you stumble upon!

**Comment by nomeata** [comment]
Ah, sorry, that line should be 
```
rename value YourModuleName.Timestamp = YourModuleName.MkTimeStamp
```
because names in edit files need to be fully qualified.

**Comment by abailly** [comment]
Many thanks! Is there a place I missed where this is documented? Or can I do a PR documenting this?

**Comment by nomeata** [comment]
“documented” – what is that? ;-)

**Comment by nomeata** [comment]
Ok, joking aside. If we start getting out-side users, we (well, they ;-)) need some form of user manual. Maybe we get around to write that once the papers are written, but there are always more papers to be written.

If you feel like contributing, then maybe adding a section “Edits” in the <README.md> file that describes all the various edits that are supported (or maybe only the commonly used once) would be useful.

**Comment by abailly** [comment]
I do feel like contributing, yes :)
