### ISSUE TITLE
Add edit to skip record selectors

### ISSUE THREAD

**Issue by sweirich** [antalsz/hs-to-coq#75]
At the first cut, skip the definition of all selectors for a specific datatype. 
For example,
```
data InstructionI =
  Lb { rd :: Register, rs1 :: Register, oimm12 :: MachineInt } |
  Lh { rd :: Register, rs1 :: Register, oimm12 :: MachineInt } 
```
the edit
```
skip selectors Decode.InstructionI
```
should suppress the generation of the selectors.

I don't think we want to suppress them individually (i.e. rd, rs1, oimm12) and in the file that this example comes from, that wouldn't work because the names of the selectors are ambiguous. (i.e. several different datatypes use `rd`)

**Comment by nomeata** [comment]
This works now (see 32e20e08994de439be5ad17cb789a153dafa0672)
