### ISSUE TITLE
Don't throw away record field names

### ISSUE THREAD

**Issue by samuelgruetter** [antalsz/hs-to-coq#79]
In the Haskell file

```
module RecordsTest where

type Register = Int
type MachineInt = Int

data InstructionI =
  Lb { rd :: Register, rs1 :: Register, oimm12 :: MachineInt } |
  Lh { rd :: Register, rs1 :: Register, oimm12 :: MachineInt }
```

`InstructionI` is translated into

```
Inductive InstructionI : Type
  := Lb : Register -> Register -> MachineInt -> InstructionI
  |  Lh : Register -> Register -> MachineInt -> InstructionI.
```

which means that the names of the fields are lost, so when I do `destruct instr` in a Coq proof where `instr` is of type `InstructionI`, Coq will auto-generate names for the fields, instead of using `rd`, `rs1`, etc.

It would be better if the output was

```
Inductive InstructionI :=
| Lb(rd: Register)(rs1: Register)(oimm12: MachineInt)
| Lh(rd: Register)(rs1: Register)(oimm12: MachineInt).
```

**Comment by nomeata** [comment]
I actually didn’t know the latter syntax. Are the names used just for variable names? I.e. no clashes when some names are used in multiple data types? Is  it equivalent to this?
```
Inductive InstructionI :=
| Lb : forall  (rd: Register)(rs1: Register)(oimm12: MachineInt), InstructionI
| Lh: forall (rd: Register)(rs1: Register)(oimm12: MachineInt), InstructionI
```

Implementation wise, this is in code that @antalsz is more familiar with than I.

**Comment by samuelgruetter** [comment]
Yes, I think it's equivalent to this
