### ISSUE TITLE
skip data constructor edit

### ISSUE THREAD

**Issue by sweirich** [antalsz/hs-to-coq#99]
We have an edit for skipping a method from a class, but we don't have a dual edit for skipping a data constructor from a datatype. 

What I'm imagining is that this code:

     data F = A | B 
     g :: F -> Int 
     g A = 1
     g B = 2

with the "skip A" edit would produce this output:

     Inductive F : Type := B. 
     Definition g (x:F) := match g with | B => 2 end.

This edit would be useful in ghc for the Var type. We want to eliminate the TyVar and TcTyVar dataconstructors so that we don't have to think about type/coercion variables.

**Comment by antalsz** [comment]
Added in e3dd4ece03f9e36f2d519ae5a12ae1bb1401bc51
